package com.shelldocs.feature.updates

object UpdatesStringRes {
    const val PAGE_TITLE = "Documentation Health"
    const val PAGE_SUBTITLE_SUFFIX = "documents need attention · Maintenance triage"
    const val SCAN_NOW = "Scan now"
    const val SCANNING = "SCANNING"
    const val TAB_HEALTH = "Documentation Health"
    const val TAB_METADATA_ISSUES = "Attributes to Review"
    const val TAB_HEALTHY = "Documentation Healthy"
    const val LOADING_PENDING_UPDATES = "LOADING"
    const val LOADING_DOCUMENTATION_HEALTH = "Scanning documentation health..."
    const val LOADING_CLASSIFYING_DOCUMENTS = "Classifying documents..."
    const val LOADING_HEALTHY_DOCUMENTS = "Loading healthy documents..."
    const val HEADER_DOCUMENT = "DOCUMENT"
    const val HEADER_MISSING = "MISSING"
    const val HEADER_SOURCE = "SOURCE"
    const val HEADER_AI_SUGGESTION = "AI SUGGESTION"
    const val HEADER_ACTIONS = "ACTIONS"
    const val HEADER_AREA = "AREA"
    const val HEADER_VERSION = "VERSION"
    const val HEADER_OWNER = "OWNER"
    const val HEADER_LAST_REVIEW = "REVIEW"
    const val HEADER_ACTION = "ACTION"
    const val EDIT = "Edit"
    const val ACCEPT = "Accept"
    const val CANCEL = "Cancel"
    const val CONFIRM = "Confirm"
    const val OPEN = "Open"
    const val NO_AI_SUGGESTION = "No AI suggestion"
    const val METADATA_REVIEW_TITLE = "Edit Attributes"
    const val METADATA_REVIEW_DESCRIPTION =
        "Review only the attributes that still need attention for this document."
    const val METADATA_CONFIRM_TITLE = "Confirm Attribute Update"
    const val METADATA_CONFIRM_DESCRIPTION = "Apply these attribute changes to the document?"
    const val METADATA_CONFIRM_CHANGES = "Changes to apply"
    const val FIELD_OWNER = "Owner"
    const val FIELD_AREA = "Area"
    const val FIELD_APPLICATION_VERSION = "Application Version"
    const val FIELD_PLATFORM = "Platform"
    const val FIELD_TAGS = "Tags"
    const val FIELD_TEAM = "Team"
    const val FIELD_MODULE = "Module"
    const val PLACEHOLDER_SELECT_AREA = "Select area"
    const val PLACEHOLDER_SELECT_VERSION = "Select version"
    const val PLACEHOLDER_COMMA_SEPARATED_TAGS = "Comma-separated tags"
    const val LABEL_SUGGESTED = "Suggested"
    const val AI_UPDATE_TITLE = "AI Suggested Update"
    const val AI_UPDATE_PREPARING = "Preparing AI Suggested Update"
    const val AI_UPDATE_CURRENT_DOCUMENT = "CURRENT DOCUMENT"
    const val AI_UPDATE_SUGGESTED_DOCUMENT = "SUGGESTED DOCUMENT"
    const val AI_UPDATE_SAVE_CHANGES = "Save Changes"
    const val AI_UPDATE_APPLYING = "Applying..."
    const val AI_UPDATE_NO_CHANGES = "No documentation changes required."
    const val AI_UPDATE_NO_CHANGES_DETAIL =
        "The current document remains valid, so there is no proposed content update to publish."
    const val AI_UPDATE_CONFIRM_TITLE = "Apply Documentation Update"
    const val AI_UPDATE_CONFIRM_BODY =
        "You are about to publish this document update.\n\nThe changes will be synchronized with all configured sources of truth and recorded in version history.\n\nThis action can be reverted later through document version history."
    const val AI_UPDATE_OWNER = "Document Owner"
    const val AI_UPDATE_CONTACT_OWNER = "Contact Owner"
}
